INSERT INTO USER(ID, LOGIN_NAME, FIRST_NAME, LAST_NAME, AGE, CREATED_AT, UPDATED_AT) VALUES
(10000, 'JohnDoe01', 'John', 'Doe', 32, SYSDATE, SYSDATE);
INSERT INTO COURSE(ID, NAME, DESCRIPTION, DURATION, STATE, PRICE, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES (100000, 'Java Basics', 'Java Fundamentals', 320, 'PUBLISHED', 300, '1001', SYSDATE, SYSDATE);
INSERT INTO COURSE(ID, NAME, DESCRIPTION, DURATION, STATE, PRICE, UPDATED_BY, CREATED_AT, UPDATED_AT)
VALUES (100001, 'JavaScript', 'JavaScript Fundamentals', 30, 'PUBLISHED', 99.9, '1002', SYSDATE, SYSDATE);
INSERT INTO AUTHOR(ID, LOGIN_NAME, FIRST_NAME, LAST_NAME, ABOUT) VALUES
(10001, 'JosephCale01', 'Joseph', 'Cale', 'Expert in Java');
INSERT INTO AUTHOR(ID, LOGIN_NAME, FIRST_NAME, LAST_NAME, ABOUT) VALUES
(10002, 'CarenWalk89', 'Caren', 'Walk', 'Expert in Microservices');
INSERT INTO COURSE_AUTHORS(COURSES_ID, AUTHORS_ID) VALUES(100000, 10001);